"""High-level NetSuite item operations built on :class:`NetSuiteClient`.

This layer is responsible for *upserting* item records and their prices /
vendor-availability fields. It is intentionally agnostic about how the records
were first created:

* For **ongoing updates** (prices, inventory availability, status, image URLs)
  the REST record API used here is ideal — fast and idempotent via external id.
* For the **initial bulk creation** of the matrix structure, NetSuite's REST
  record API has well-known limitations around building parent/child matrix
  option lists. The recommended path is a one-time CSV import generated by
  :mod:`sanmar_netsuite.transform.csv_export`, after which this repository keeps
  everything in sync. See ``docs/NETSUITE_SETUP.md``.

External-id convention:
    parent (style)  -> ``SANMAR-<STYLE>``           e.g. ``SANMAR-K420``
    child  (sku)    -> ``SANMAR-<UNIQUE_KEY>``       e.g. ``SANMAR-92033``
"""

from __future__ import annotations

import logging
from typing import Any

from ..config import NetSuiteConfig
from .client import NetSuiteClient, NetSuiteError

log = logging.getLogger(__name__)

ITEM_RECORD_TYPE = "inventoryItem"


def _sql_escape(value: str) -> str:
    """Escape a string literal for inline use in a SuiteQL ``WHERE`` clause.

    SanMar keys are alphanumeric, but escape single quotes defensively so a
    crafted value can't break out of the literal.
    """
    return value.replace("'", "''")


def parent_external_id(style: str) -> str:
    return f"SANMAR-{style.strip().upper()}"


def child_external_id(unique_key: str) -> str:
    return f"SANMAR-{unique_key.strip()}"


class ItemRepository:
    def __init__(self, client: NetSuiteClient, config: NetSuiteConfig) -> None:
        self._client = client
        self._config = config
        self._fields = config.fields

    # ── lookups ──────────────────────────────────────────────────────────────
    def find_id_by_external_id(self, external_id: str) -> str | None:
        """Resolve a NetSuite internal id from an external id via SuiteQL."""
        rows = self._client.suiteql(
            f"SELECT id FROM item WHERE externalid = '{_sql_escape(external_id)}'"
        )
        return str(rows[0]["id"]) if rows else None

    def find_id_by_unique_key(self, unique_key: str) -> str | None:
        """Resolve internal id by the SanMar unique-key custom field."""
        field = self._fields.unique_key
        rows = self._client.suiteql(
            f"SELECT id FROM item WHERE {field} = '{_sql_escape(unique_key)}'"
        )
        return str(rows[0]["id"]) if rows else None

    # ── upserts ──────────────────────────────────────────────────────────────
    def upsert(self, external_id: str, body: dict[str, Any]) -> str:
        """Upsert an item record by external id; returns its internal id."""
        try:
            return self._client.upsert_by_external_id(ITEM_RECORD_TYPE, external_id, body)
        except NetSuiteError as exc:
            log.error("Upsert failed for %s: %s", external_id, exc)
            raise

    def update_fields(self, internal_id: str, body: dict[str, Any]) -> None:
        """PATCH a subset of fields onto an existing item by internal id."""
        self._client.update_record(ITEM_RECORD_TYPE, internal_id, body)
